import assert from "node:assert/strict";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { createPingResponse } from "../src/shared/rpc";
import { createDesktopService } from "../src/bun/desktopService";

const result = createPingResponse("request-1", "1.4.2");
assert.deepEqual(result, { nonce: "request-1", runtime: "bun", version: "1.4.2" });
assert.deepEqual(Object.keys(result), ["nonce", "runtime", "version"]);
const webviewSource = readFileSync(join(import.meta.dir, "../src/mainview/App.vue"), "utf8");
assert.match(webviewSource, /sandbox=""/);
assert.doesNotMatch(webviewSource, /node:fs|node:child_process|loadEntryModule|loadInputValues|preparePdfReport|serializePdfReport|Bun\./);
console.log("Typed RPC and webview boundary contract passed (4 assertions)");

const root = mkdtempSync(join(tmpdir(), "openamx-desktop-"));
mkdirSync(join(root, "nested"));
const entry = join(root, "main.amx");
writeFileSync(entry, "# Saved\n\n```amx\nlet value = 1\n```\n");
writeFileSync(join(root, "nested", "module.amx"), "```amx\nlet value = 2\n```");
const outside = join(tmpdir(), `openamx-outside-${Date.now()}.amx`);
writeFileSync(outside, "```amx\nlet value = 3\n```");
symlinkSync(outside, join(root, "nested", "outside.amx"));

const service = createDesktopService();
const project = await service.request.openProject({ path: root });
assert.equal(project.ok, true);
const opened = await service.request.openDocument({ path: entry });
assert.equal(opened.ok, true);
if (!opened.ok) throw new Error(opened.error.message);
const changed = await service.request.updateBuffer({ text: "# Unsaved\n\n```amx\nlet value = 42\n```\n" });
assert.equal(changed.ok, true);
if (!changed.ok) throw new Error(changed.error.message);
assert.equal(changed.document.dirty, true);
const preview = await service.request.previewBuffer();
assert.equal(preview.ok, true);
if (!preview.ok) throw new Error(preview.error.message);
assert.match(preview.html, /Unsaved/);
const files = await service.request.listProjectFiles();
assert.equal(files.ok, true);
if (!files.ok) throw new Error(files.error.message);
assert.deepEqual(files.files.map(file => file.path).sort(), ["main.amx", "nested/module.amx"]);
const rejected = await service.request.openDocument({ path: outside });
assert.equal(rejected.ok, false);
writeFileSync(entry, "# Changed elsewhere\n");
const conflict = await service.request.saveDocument();
assert.equal(conflict.ok, false);
if (conflict.ok) throw new Error("Expected a save conflict");
assert.equal(conflict.error.code, "DESKTOP_CONFLICT");
await service.request.updateBuffer({ text: "```amx\nlet value = 1\n" });
const diagnostics = await service.request.analyzeBuffer();
assert.equal(diagnostics.ok, true);
if (!diagnostics.ok) throw new Error(diagnostics.error.message);
assert.equal(diagnostics.analysis.diagnostics[0]?.code, "AMX3001");
console.log("Desktop session contract passed (11 assertions)");

const dataRoot = join(root, "data");
mkdirSync(dataRoot);
const entrySource = `# Analysis\n\n\`\`\`amx\nimport { Row, addTen } from "./nested/module.amx"\ninput amounts: Number[]\ninput rows: Row[]\nexport let result: Number = addTen(sum(amounts) + sum(for row in rows {\n  return row.amount\n}))\n\`\`\`\n`;
const savedSource = `# Analysis\n\n\`\`\`amx\nimport { Row, addTen } from "./nested/module.amx"\ninput amounts: Number[]\ninput rows: Row[]\nexport let result: Number = addTen(1)\n\`\`\`\n`;
writeFileSync(entry, savedSource);
writeFileSync(join(root, "nested", "module.amx"), `\`\`\`amx\nexport type Row {\n  amount: Number\n}\nexport fn addTen(value: Number): Number = value + 10\n\`\`\`\n`);
writeFileSync(join(dataRoot, "amounts.json"), "[2, 3]");
writeFileSync(join(dataRoot, "rows.csv"), "amount\n4\n6\n");
const reopened = await service.request.openDocument({ path: entry });
assert.equal(reopened.ok, true);
const unsaved = await service.request.updateBuffer({ text: entrySource });
assert.equal(unsaved.ok, true);
const invalidValidation = await service.request.runBuffer({ validation: "invalid" as "aggregate" });
assert.equal(invalidValidation.ok, true);
if (!invalidValidation.ok) throw new Error(invalidValidation.error.message);
assert.equal(invalidValidation.diagnostics[0]?.code, "AMX4001");
const run = await service.request.runBuffer({
	inputMappings: [`amounts=${join(dataRoot, "amounts.json")}`, `rows=${join(dataRoot, "rows.csv")}`]
});
assert.equal(run.ok, true);
if (!run.ok) throw new Error(run.error.message);
assert.deepEqual(run.diagnostics, []);
assert.deepEqual(run.summary.values.find(value => value.name === "result"), { name: "result", value: 25 });
assert.deepEqual(run.summary.values.map(value => value.name), ["result"]);
assert.equal(readFileSync(entry, "utf8"), savedSource);

const projectConfigDirectory = join(root, ".openamx");
mkdirSync(projectConfigDirectory);
const localConfigPath = join(projectConfigDirectory, "local.json");
const projectAmounts = join(dataRoot, "project-amounts.json");
const localAmounts = join(dataRoot, "local-amounts.json");
const perRunAmounts = join(dataRoot, "per-run-amounts.json");
writeFileSync(projectAmounts, "[1]");
writeFileSync(localAmounts, "[2]");
writeFileSync(perRunAmounts, "[3]");
writeFileSync(join(projectConfigDirectory, "project.json"), JSON.stringify({ version: 1, inputs: { amounts: "data/project-amounts.json", rows: "data/rows.csv" } }));
writeFileSync(localConfigPath, JSON.stringify({ version: 1, inputs: { amounts: "data/local-amounts.json" } }));
if (process.platform !== "win32") chmodSync(localConfigPath, 0o600);
const inputConfig = await service.request.getInputConfiguration();
assert.equal(inputConfig.ok, true);
if (!inputConfig.ok) throw new Error(inputConfig.error.message);
assert.deepEqual(inputConfig.configuration.inputs, [
	{ name: "amounts", source: "local" },
	{ name: "rows", source: "project" }
]);
if (process.platform !== "win32") {
	chmodSync(localConfigPath, 0o644);
	const insecureConfig = await service.request.getInputConfiguration();
	assert.equal(insecureConfig.ok, true);
	if (!insecureConfig.ok) throw new Error(insecureConfig.error.message);
	assert.match(insecureConfig.configuration.diagnostics[0]?.message ?? "", /permissions/);
	chmodSync(localConfigPath, 0o600);
}
const localRun = await service.request.runBuffer();
assert.equal(localRun.ok, true);
if (!localRun.ok) throw new Error(localRun.error.message);
assert.equal(localRun.summary.values.find(value => value.name === "result")?.value, 22);
const perRun = await service.request.runBuffer({ inputMappings: [`amounts=${perRunAmounts}`] });
assert.equal(perRun.ok, true);
if (!perRun.ok) throw new Error(perRun.error.message);
assert.equal(perRun.summary.values.find(value => value.name === "result")?.value, 23);
writeFileSync(localConfigPath, JSON.stringify({ version: 1, inputs: {} }));
const projectRun = await service.request.runBuffer();
assert.equal(projectRun.ok, true);
if (!projectRun.ok) throw new Error(projectRun.error.message);
assert.equal(projectRun.summary.values.find(value => value.name === "result")?.value, 21);

const traversalTarget = join(tmpdir(), `openamx-traversal-${Date.now()}.json`);
writeFileSync(traversalTarget, "[9]");
writeFileSync(join(projectConfigDirectory, "project.json"), JSON.stringify({ version: 1, inputs: { amounts: relative(root, traversalTarget), rows: "data/rows.csv" } }));
const traversedConfig = await service.request.getInputConfiguration();
assert.equal(traversedConfig.ok, true);
if (!traversedConfig.ok) throw new Error(traversedConfig.error.message);
assert.match(traversedConfig.configuration.diagnostics[0]?.message ?? "", /inside the project/);
const projectLink = join(dataRoot, "external.json");
symlinkSync(traversalTarget, projectLink);
writeFileSync(join(projectConfigDirectory, "project.json"), JSON.stringify({ version: 1, inputs: { amounts: "data/external.json", rows: "data/rows.csv" } }));
const linkedConfig = await service.request.getInputConfiguration();
assert.equal(linkedConfig.ok, true);
if (!linkedConfig.ok) throw new Error(linkedConfig.error.message);
assert.match(linkedConfig.configuration.diagnostics[0]?.message ?? "", /inside the project/);
unlinkSync(projectLink);

writeFileSync(join(projectConfigDirectory, "project.json"), JSON.stringify({ version: 1, inputs: { amounts: "data/project-amounts.json", rows: "data/rows.csv" }, unexpected: true }));
const invalidConfig = await service.request.getInputConfiguration();
assert.equal(invalidConfig.ok, true);
if (!invalidConfig.ok) throw new Error(invalidConfig.error.message);
assert.equal(invalidConfig.configuration.diagnostics[0]?.code, "DESKTOP_CONFIG");
writeFileSync(join(projectConfigDirectory, "project.json"), JSON.stringify({ version: 1, inputs: { amounts: "data/project-amounts.json", rows: "data/rows.csv" } }));

const invalidPrivateInput = join(tmpdir(), `openamx-private-${Date.now()}.json`);
writeFileSync(localConfigPath, JSON.stringify({ version: 1, inputs: { amounts: invalidPrivateInput } }));
const privateFailure = await service.request.runBuffer();
assert.equal(privateFailure.ok, true);
if (!privateFailure.ok) throw new Error(privateFailure.error.message);
assert.equal(privateFailure.diagnostics[0]?.code, "AMX4001");
assert.equal(privateFailure.diagnostics.some(item => item.message.includes(invalidPrivateInput)), false);

writeFileSync(localConfigPath, JSON.stringify({ version: 1, inputs: {} }));
writeFileSync(projectAmounts, "{");
writeFileSync(join(dataRoot, "rows.csv"), "unknown\nvalue\n");
const aggregate = await service.request.runBuffer();
assert.equal(aggregate.ok, true);
if (!aggregate.ok) throw new Error(aggregate.error.message);
assert.ok(aggregate.diagnostics.length >= 2);
assert.deepEqual(aggregate.summary.values, []);
const failFast = await service.request.runBuffer({ validation: "fail-fast" });
assert.equal(failFast.ok, true);
if (!failFast.ok) throw new Error(failFast.error.message);
assert.equal(failFast.diagnostics.length, 1);

writeFileSync(projectAmounts, "[1]");
writeFileSync(join(dataRoot, "rows.csv"), "amount\n4\n6\n");
const previewWithInputs = await service.request.previewBuffer();
assert.equal(previewWithInputs.ok, true);
if (!previewWithInputs.ok) throw new Error(previewWithInputs.error.message);
assert.deepEqual(previewWithInputs.diagnostics, []);
const reportDirectory = join(root, "reports");
mkdirSync(reportDirectory);
const htmlPath = join(reportDirectory, "analysis.html");
const htmlSave = await service.request.saveHtml({ path: "reports/analysis.html" });
assert.equal(htmlSave.ok, true);
if (!htmlSave.ok) throw new Error(htmlSave.error.message);
assert.equal(htmlSave.path, htmlPath);
assert.equal(readFileSync(htmlPath, "utf8"), previewWithInputs.html);
const pdfPath = join(reportDirectory, "analysis.pdf");
const pdfExport = await service.request.exportPdf({ path: "reports/analysis.pdf" });
assert.equal(pdfExport.ok, true);
if (!pdfExport.ok) throw new Error(pdfExport.error.message);
assert.equal(pdfExport.path, pdfPath);
assert.ok(pdfExport.bytes > 1000);
assert.match(readFileSync(pdfPath).toString("utf8", 0, 4), /^%PDF$/);

const invalidSource = "```amx\nlet incomplete =\n```\n";
await service.request.updateBuffer({ text: invalidSource });
writeFileSync(htmlPath, "preserve-html");
writeFileSync(pdfPath, "preserve-pdf");
const failedHtml = await service.request.saveHtml({ path: "reports/analysis.html" });
assert.equal(failedHtml.ok, true);
if (!failedHtml.ok) throw new Error(failedHtml.error.message);
assert.equal(failedHtml.diagnostics.length, 1);
assert.equal(readFileSync(htmlPath, "utf8"), "preserve-html");
const failedPreview = await service.request.previewBuffer();
assert.equal(failedPreview.ok, true);
if (!failedPreview.ok) throw new Error(failedPreview.error.message);
assert.equal(failedPreview.html, "");
assert.equal(failedPreview.diagnostics.length, 1);
const failedPdf = await service.request.exportPdf({ path: "reports/analysis.pdf" });
assert.equal(failedPdf.ok, true);
if (!failedPdf.ok) throw new Error(failedPdf.error.message);
assert.equal(failedPdf.diagnostics.length, 1);
assert.equal(readFileSync(pdfPath, "utf8"), "preserve-pdf");
const htmlLink = join(reportDirectory, "linked.html");
await service.request.updateBuffer({ text: entrySource });
symlinkSync(htmlPath, htmlLink);
const rejectedHtmlLink = await service.request.saveHtml({ path: "reports/linked.html" });
assert.equal(rejectedHtmlLink.ok, true);
if (!rejectedHtmlLink.ok) throw new Error(rejectedHtmlLink.error.message);
assert.equal(rejectedHtmlLink.diagnostics[0]?.code, "AMX6001");
assert.equal(existsSync(htmlLink), true);
const outsideHtml = await service.request.saveHtml({ path: join(tmpdir(), `outside-${Date.now()}.html`) });
assert.equal(outsideHtml.ok, true);
if (!outsideHtml.ok) throw new Error(outsideHtml.error.message);
assert.equal(outsideHtml.diagnostics[0]?.code, "AMX6001");
const missingParentPdf = await service.request.exportPdf({ path: "missing/analysis.pdf" });
assert.equal(missingParentPdf.ok, true);
if (!missingParentPdf.ok) throw new Error(missingParentPdf.error.message);
assert.equal(missingParentPdf.diagnostics[0]?.code, "AMX6001");
assert.equal(readFileSync(pdfPath, "utf8"), "preserve-pdf");
assert.equal(readFileSync(entry, "utf8"), savedSource);
console.log("Desktop workflow contract passed (precedence, validation, current-buffer, HTML/PDF safety)");