import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createPingResponse } from "../src/shared/rpc";
import { createDesktopService } from "../src/bun/desktopService";

const result = createPingResponse("request-1", "1.4.2");
assert.deepEqual(result, { nonce: "request-1", runtime: "bun", version: "1.4.2" });
assert.deepEqual(Object.keys(result), ["nonce", "runtime", "version"]);
console.log("Typed RPC payload contract passed (2 assertions)");

const root = mkdtempSync(join(tmpdir(), "openamx-desktop-"));
mkdirSync(join(root, "nested"));
const entry = join(root, "main.amx");
writeFileSync(entry, "# Saved\n\n```amx\nlet value = 1\n```\n");
writeFileSync(join(root, "nested", "module.amx"), "```amx\nlet value = 2\n```");
const outside = join(tmpdir(), `openamx-outside-${Date.now()}.amx`);
writeFileSync(outside, "```amx\nlet value = 3\n```");
symlinkSync(outside, join(root, "nested", "outside.amx"));

const service = createDesktopService();
const project = await service.request.openProject({ path: root });
assert.equal(project.ok, true);
const opened = await service.request.openDocument({ path: entry });
assert.equal(opened.ok, true);
if (!opened.ok) throw new Error(opened.error.message);
const changed = await service.request.updateBuffer({ text: "# Unsaved\n\n```amx\nlet value = 42\n```\n" });
assert.equal(changed.ok, true);
if (!changed.ok) throw new Error(changed.error.message);
assert.equal(changed.document.dirty, true);
const preview = await service.request.previewBuffer();
assert.equal(preview.ok, true);
if (!preview.ok) throw new Error(preview.error.message);
assert.match(preview.html, /Unsaved/);
const files = await service.request.listProjectFiles();
assert.equal(files.ok, true);
if (!files.ok) throw new Error(files.error.message);
assert.deepEqual(files.files.map(file => file.path).sort(), ["main.amx", "nested/module.amx"]);
const rejected = await service.request.openDocument({ path: outside });
assert.equal(rejected.ok, false);
writeFileSync(entry, "# Changed elsewhere\n");
const conflict = await service.request.saveDocument();
assert.equal(conflict.ok, false);
if (conflict.ok) throw new Error("Expected a save conflict");
assert.equal(conflict.error.code, "DESKTOP_CONFLICT");
await service.request.updateBuffer({ text: "```amx\nlet value = 1\n" });
const diagnostics = await service.request.analyzeBuffer();
assert.equal(diagnostics.ok, true);
if (!diagnostics.ok) throw new Error(diagnostics.error.message);
assert.equal(diagnostics.analysis.diagnostics[0]?.code, "AMX3001");
console.log("Desktop session contract passed (11 assertions)");